version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "57:0d:3a:ff:da:c8:9e:71:dc:d1:35:91:7c:f7:50:42"
      - checkout
      - run: docker login --username=$DOCKER_USER --password=$DOCKER_PASS cloud.canister.io:5000
      - run: docker build -t cloud.canister.io:5000/nicrom/veinteapp:$CIRCLE_SHA1 .
      - run: docker push cloud.canister.io:5000/nicrom/veinteapp:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no nicrom@35.192.146.6 "/bin/bash /home/nicrom/veinte-deployer/deploy-fronted.sh $CIRCLE_SHA1"          